Integrate signup with GitHub
annonymousauthority/P2PCoder pull request #115
Opened 2023-05-30 13:37 UTC by Remi-dee

### This PR resolves #114 
## Task
- [x] Integrate Signup with Github to the app

![P2PCoderGif311111](https://github.com/annonymousauthority/P2PCoder/assets/96704300/1e89d9ac-f6bf-4bd4-a913-a751c786d792)

![Screenshot 2023-05-31 140709](https://github.com/annonymousauthority/P2PCoder/assets/96704300/2534363b-8966-4c0f-819e-86a42ec4c1ef)

2023-05-30 17:52 UTC, annonymousauthority requested changes

2023-05-30 17:52 UTC, annonymousauthority commented on src/composables/verifySignedIn.js
> +const user = appAuth.currentUser;
Why change the line?

2023-05-31 09:40 UTC, Remi-dee commented on src/components/signup_comp.js
i made an update.

2023-05-31 10:05 UTC, annonymousauthority requested changes

2023-05-31 10:05 UTC, annonymousauthority commented on src/composables/auth_github_signin_popup.js
This function won't work for signup with Github...
Could you check it completely?

2023-05-31 10:28 UTC, Remi-dee commented on src/composables/auth_github_signin_popup.js
Alright, will do.

2023-05-31 21:35 UTC, Remi-dee commented on src/components/userLogin_comp.js
> +            onClick={signInWithGithub}
For some weird reason, the button doesnt trigger the `onclick` function at times, it rather just reload the page, still trying to figure why that is

2023-05-31 21:38 UTC, Remi-dee commented on src/composables/auth_github_signin_popup.js
I've updated my request,
The function is working now, after i'd set in all necessary values in the console and app

2023-06-01 09:51 UTC, annonymousauthority approved these changes
LG

2023-06-01 09:51 UTC, merged