Taylor - Signup Form validation & Binding Signup Function
annonymousauthority/P2PCoder pull request #117
Opened 2023-05-31 15:51 UTC by TaylorDJones11

## What type of PR is this? (check all applicable)

- [ ] Feature
- [ ] Refactor
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [x] Other: Form Validation & Binding Signup Function
  
  
## Description of what this Pull Request does
- Adding form validation for the signup form
- Binding the Firebase signup function to the form component
- 

## Related Tickets & Documents
-Closes: #113 

  
## QA Instructions, Screenshots, Recording

- ROADBLOCKS
- I changed the Link to a button because I wasn't able to catch the form validation otherwise, it would send me straight to the main page. 
- I lost one aspect of the toggle icon function, when the password is visible in the input and a user erases it completely, the icon no longer goes back to the default state of the open icon. I displayed this in the last part of the gif.

![SignupForm](https://github.com/annonymousauthority/P2PCoder/assets/72883059/1fb6aebf-2b98-4ba3-b5c8-921119b7ee40)

2023-05-31 20:48 UTC, annonymousauthority requested changes
Look at the validation function properly

2023-05-31 20:48 UTC, annonymousauthority commented on src/composables/signupFormValidation.js
Didn't @DeborahIhesiaba create a form validation function?

2023-05-31 21:05 UTC, TaylorDJones11 commented on src/composables/signupFormValidation.js
Yes, but it only covers email/password. Do I then add to her function to cover first name, last name, username, and confirm password?

2023-05-31 21:37 UTC, annonymousauthority commented on src/composables/signupFormValidation.js
Yes please, let's have one area of concern

2023-06-01 07:24 UTC, TaylorDJones11 commented
> Look at the validation function properly

What exactly am I looking for? Am I not catching the errors correctly? Adding more edge cases like "user already exists"?

2023-06-01 14:00 UTC, annonymousauthority approved these changes
LG

2023-06-01 14:01 UTC, merged