178 user should be able to create account and users need to verify account before signing in features
annonymousauthority/P2PCoder pull request #192
Opened 2023-06-13 09:59 UTC by OladipoOmotosho

Two features implemented are :
 Users can now create account ,
 Users need to verify account before they can sign in.
 
 Additional comments :
 the email field in Sign Up page shows "Email available for every email even when the email has already being taken, i have tried resolving the bug but to no avail kindly take a look at it"

2023-06-13 14:27 UTC, OladipoOmotosho commented
![20230613_152542.gif](https://github.com/annonymousauthority/P2PCoder/assets/65185499/bfb1a183-1441-48c8-bc49-81506278f95f)

2023-06-13 18:29 UTC, Oyinbrakemigrace submitted a review, later dismissed
LGTM

2023-06-14 11:53 UTC, TaylorDJones11 commented
> Two features implemented are : Users can now create account , Users need to verify account before they can sign in.
> 
> Additional comments : the email field in Sign Up page shows "Email available for every email even when the email has already being taken, i have tried resolving the bug but to no avail kindly take a look at it"

The original code for the signup form doesn't have a conditional to check if the email is available in real-time like the username, only unavailable after the user creates the account as "Email already in use". So why is it highlighting green here? Do you think it should be added the same as the username?

2023-06-14 12:33 UTC, annonymousauthority commented
> LGTM

How is it good when there's a query?

2023-06-18 15:13 UTC, OladipoOmotosho commented
![email verification](https://github.com/annonymousauthority/P2PCoder/assets/65185499/59d48b45-35f1-4076-b9dc-cc602d1a2db6)

a video showing implementation of the verification modal

2023-06-19 08:43 UTC, Remi-dee requested changes, later dismissed

2023-06-20 19:44 UTC, Remi-dee requested changes, later dismissed

2023-06-20 19:44 UTC, Remi-dee commented on development/src/components/VerificationOverlay.js
> +// import { triggerEmailVerification } from "@/composables/authSignupFunction";
Please take out the comments

2023-06-20 19:44 UTC, Remi-dee commented on development/src/components/VerificationOverlay.js
> +  // const router = useRouter();
Kindly take out all comments

2023-06-20 19:44 UTC, Remi-dee commented on development/src/components/welcome_comp.js
> +      <Modal
This shouldn’t be on welcome page, it should be applied in `page.js` as the verification modal won’t be visible if welcome page is closed when you try to route to the `verificationOverlay`.

2023-06-21 06:38 UTC, OladipoOmotosho commented on development/src/components/VerificationOverlay.js
> +// import { triggerEmailVerification } from "@/composables/authSignupFunction";
done

2025-04-03 10:23 UTC, closed without merging