Warning error at tab limit of 5
annonymousauthority/P2PCoder pull request #193
Opened 2023-06-13 16:16 UTC by DeborahIhesiaba

What type of PR is this? (check all applicable)
- [ ] Feature
- [ ] Refactor
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [x] Other: 

Description of what this Pull Request does
A warning error shows up when a user tries to create more than five tabs

Related Tickets & Documents
Closes #184 

QA Recordings
![modal](https://github.com/annonymousauthority/P2PCoder/assets/36891350/a2beb37b-2bcf-4358-94e8-5bda339dffd9)

2023-06-13 16:23 UTC, annonymousauthority requested changes
Why is the package-lock.json modified?

2023-06-13 16:34 UTC, 7malikk approved these changes

2023-06-13 16:39 UTC, DeborahIhesiaba commented
> Why is the package-lock.json modified?

I uninstalled react toastify package

2023-06-15 11:07 UTC, 7malikk approved these changes

2023-06-15 11:09 UTC, annonymousauthority approved these changes
OK Cautionary merge

2023-06-15 11:09 UTC, merged