codes persist upon refresh and unique to each tab
annonymousauthority/P2PCoder pull request #196
Opened 2023-06-14 14:26 UTC by 7malikk

## Description of what this Pull Request does
- [x] Codes persist upon refresh.
- [x] The user can write tab-specific codes.

## Related Issue
#180 
Closes #191 

## Recording
![persists](https://github.com/annonymousauthority/P2PCoder/assets/75104021/a73c7238-db58-4168-a0de-4d59643e0546)

2023-06-14 14:28 UTC, DeborahIhesiaba approved these changes

2023-06-14 18:59 UTC, annonymousauthority requested changes
You haven't updated collab variable using useeffect and usestate

2023-06-14 19:06 UTC, babblebey commented on development/src/components/codingEditor.js
> +    items.filter((e) => e.active)[0].code = newValue;
This stores code state in `localStorage` item object `code` onChange to allow code state persistence. Great! 

This same function can simultaneously keep code state in a DB `document` specific to the collaboration session too at some point. I guess @Remi-dee is working on that!!

LG!

2023-06-14 21:34 UTC, annonymousauthority approved these changes
LG

2023-06-14 21:34 UTC, merged

2023-06-15 01:02 UTC, annonymousauthority approved these changes
LG