Taylor - adding user to existing session
annonymousauthority/P2PCoder pull request #213
Opened 2023-06-16 20:21 UTC by TaylorDJones11

## Description of what this Pull Request does
- Adds User to Existing Session

## Related Tickets & Documents
- Closes #212 

## Screenshots
![AddUserToSession](https://github.com/annonymousauthority/P2PCoder/assets/72883059/fc994544-0f93-49b9-9a61-3986d93cf924)
<img width="411" alt="Screenshot 2023-06-16 at 22 11 29" src="https://github.com/annonymousauthority/P2PCoder/assets/72883059/ff8dadd6-66ac-4a60-946f-a21f54e57002">

2023-06-17 12:19 UTC, annonymousauthority requested changes

2023-06-17 12:19 UTC, annonymousauthority commented on development/src/composables/addUserToSession.js
> +      users: arrayUnion(user),
is `user` filed an array?

2023-06-17 12:19 UTC, annonymousauthority commented on development/src/components/joinSession_Comp.js
There's no need for `console.log()` unless during testing

2023-06-17 20:43 UTC, Remi-dee requested changes

2023-06-17 20:43 UTC, Remi-dee commented on development/src/components/joinSession_Comp.js
> +    const hardcodedSessionId = "76cH5HyEWEhglasWBLl9";
This will be provided from joinSession modal, you can just pass it in as a parameter

2023-06-18 22:21 UTC, Remi-dee submitted a review, later dismissed
LGTM

2023-06-19 14:49 UTC, Remi-dee approved these changes

2023-06-20 15:33 UTC, annonymousauthority approved these changes
LG

2023-06-20 15:33 UTC, merged