Created a function to reset Account using firebase
annonymousauthority/P2PCoder pull request #26
Opened 2023-05-15 20:21 UTC by OladipoOmotosho

Created a function to reset Account using firebase

2023-05-15 20:48 UTC, annonymousauthority requested changes

2023-05-15 20:48 UTC, annonymousauthority commented on src/composables/resetAccountWithFirebase.js
> +import { getAuth, updateEmail, updatePassword } from "firebase/auth"
there's already an named export that is firebase configured, use that not `getAuth`

2023-05-15 20:48 UTC, annonymousauthority commented on src/composables/resetAccountWithFirebase.js
> +        const user = auth.currentUser;
The initial comment should reflect here

2023-05-15 20:48 UTC, annonymousauthority commented on src/composables/resetAccountWithFirebase.js
This entire function doesn't solve the issue that was opened.

Could you address this

2023-05-16 17:50 UTC, closed without merging

2023-05-16 17:50 UTC, OladipoOmotosho commented
Function written did not address the issue opened