Taylor- Creating signup component
annonymousauthority/P2PCoder pull request #59
Opened 2023-05-19 13:54 UTC by TaylorDJones11

## What type of PR is this? (check all applicable)

- [ ] Feature
- [ ] Refactor
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [x] Other: Creating Signup Component 
  
  
## Description of what this Pull Request does
- The Signup Component is styled with Tailwind to take in the user's information: First & Last name, Email, Username, Password, and password confirmation. 
- The Signup Component  will allow the user to create an account using Google, Github or through Email

## Related Tickets & Documents
- Closes https://github.com/annonymousauthority/P2PCoder/issues/37

  
## QA Instructions, Screenshots, Recordings
<img width="602" alt="Screenshot 2023-05-19 at 15 15 44" src="https://github.com/annonymousauthority/P2PCoder/assets/72883059/7707c14b-6ea8-443d-afc4-6215a3aef831">

2023-05-19 13:55 UTC, TaylorDJones11 commented
- I'm having issues with finding the correct spacing between the columns using flex. 
- I don't know where to find the icon components

2023-05-19 15:58 UTC, annonymousauthority requested changes

2023-05-19 15:58 UTC, annonymousauthority commented on src/components/signup_comp.js
> +      {/* Signup Form */}
No need for comments

2023-05-19 16:07 UTC, TaylorDJones11 commented
I implemented the changes you suggested at the meeting and this is the outcome 😭


<img width="1513" alt="Screenshot 2023-05-19 at 18 02 45" src="https://github.com/annonymousauthority/P2PCoder/assets/72883059/404bf8c5-6086-49c1-bbaf-a9058211a08e">

2023-05-20 08:13 UTC, TaylorDJones11 commented
Another question @annonymousauthority  when I change anything in the parent div, why does it never affect the first child div but the following ones? 

<img width="278" alt="Screenshot 2023-05-20 at 10 10 21" src="https://github.com/annonymousauthority/P2PCoder/assets/72883059/8e4b60c3-31d6-4bc2-963a-4d3a514c4e0c">

2023-05-20 09:03 UTC, Remi-dee commented
Hi @TaylorDJones11 hoping you’ve solved these?
However I’ll be willing to help, if you need any.

2023-05-20 13:27 UTC, annonymousauthority approved these changes
Well done. LGTM

2023-05-20 13:27 UTC, merged