Created a view component for the forgot Password form
annonymousauthority/P2PCoder pull request #60
Opened 2023-05-19 14:41 UTC by OladipoOmotosho

Created a view component for the forgot Password form

2023-05-19 16:01 UTC, annonymousauthority commented on src/components/ForgotPasswordForm_comp.jsx
> +const ForgotPassword_comp = () => {
No need for `_comp`
`ForgotPassword` is enough

2023-05-19 16:03 UTC, annonymousauthority commented on src/components/ForgotPasswordForm_comp.jsx
Please could you be consistent with the extension?
`.jsx` --> `.js`

2023-05-19 22:23 UTC, annonymousauthority requested changes

2023-05-19 22:23 UTC, annonymousauthority commented on src/components/ForgotPassword.js
> +        <Image src={reset} alt="reset" />
This should betton not an image. 

the button would wrap an image

2023-05-19 22:23 UTC, annonymousauthority commented on src/components/ForgotPassword.js
> +      <span>
Please utilize a div here and use a `flex` and `justify between` and `w-full` here

2023-05-19 22:23 UTC, annonymousauthority commented on src/components/ForgotPassword.js
> +        <label
You label should point to a htmlFor

2023-05-19 22:23 UTC, annonymousauthority commented on src/components/ForgotPassword.js
> +        <input
You input should have a name and id.
And the `type` should be an `email` not a `text`

2023-05-21 19:32 UTC, OladipoOmotosho commented
![Screenshot (144)](https://github.com/annonymousauthority/P2PCoder/assets/65185499/6864ef3c-3461-47ce-a5d7-d3b769683f20)
![Screenshot (143)](https://github.com/annonymousauthority/P2PCoder/assets/65185499/8ef9581e-9dfb-4ace-b25d-1cd504538eff)

2023-05-21 19:33 UTC, OladipoOmotosho commented
Screenshots attached above

2023-05-21 20:56 UTC, OladipoOmotosho commented
![Screenshot (148)](https://github.com/annonymousauthority/P2PCoder/assets/65185499/43fa6930-d0a1-4359-9f61-43930336ea16)
![Screenshot (150)](https://github.com/annonymousauthority/P2PCoder/assets/65185499/2d5e4609-4dd5-4db3-bcbe-c9c49939a929)

2023-05-21 20:57 UTC, OladipoOmotosho commented
I added the black background for better visibility but I've removed it after taking the screenshot so it's not in the code I just pushed

2023-05-21 21:19 UTC, annonymousauthority approved these changes
LG. Although I couldn't find the padding update

2023-05-21 21:19 UTC, merged

2023-05-21 22:50 UTC, OladipoOmotosho commented
I added it, I also attached screenshots of how it looks now as a commentSent from my T-Mobile 4G LTE Device
-------- Original message --------From: Augustine Francis ***@***.***> Date: 5/21/23  10:19 PM  (GMT+01:00) To: annonymousauthority/P2PCoder ***@***.***> Cc: Oladipo Omotosho ***@***.***>, Author ***@***.***> Subject: Re: [annonymousauthority/P2PCoder] Created a view component for the forgot Password form (PR #60) 
@annonymousauthority approved this pull request.

LG. Although I couldn't find the padding update

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>