Linked the tab bar to components
annonymousauthority/P2PCoder pull request #87
Opened 2023-05-23 12:59 UTC by DeborahIhesiaba

What type of PR is this? (check all applicable)
[ ] Feature
[ ] Refactor
[ ] Bug Fix
[x] Optimization
[ ] Documentation Update
[ ] Other:

Description of what this Pull Request does
The tab bar is linked to the welcome component and the terminal component. The first tab connects to the welcome component and subsequent tabs is linked to the terminal component.

Related Tickets & Documents
Closes https://github.com/annonymousauthority/P2PCoder/issues/74

QA Instructions, Screenshots, Recordings
![tabbar](https://github.com/annonymousauthority/P2PCoder/assets/36891350/a5c2796f-4b8b-4295-9978-9ffea2c920c7)

2023-05-23 17:50 UTC, annonymousauthority requested changes

2023-05-23 17:50 UTC, annonymousauthority commented on src/app/page.js
> +            <Welcome />
I can't find this components

2023-05-23 17:50 UTC, annonymousauthority commented on src/app/page.js
> +          ) : items[0]?.active && items[0].title === "Welcome" ? (
This isn't feel right

2023-05-23 17:50 UTC, annonymousauthority commented on src/app/page.js
> +            <Welcome />
Could you turn this back to just `<div>` 
And not a custom component. You can give it a color so we know and tell it's working

2023-05-23 17:50 UTC, annonymousauthority commented on src/app/page.js
> +        <div className="ml-24 w-full h-96 bg-violet-500 p-5">
I don't think your logic is exactly working. Could you look into this again?

2023-05-25 13:28 UTC, DeborahIhesiaba commented
![tabbar](https://github.com/annonymousauthority/P2PCoder/assets/36891350/f7687cce-142f-4e28-a10f-cbd60f4c6b01)

2023-05-25 13:51 UTC, 7malikk approved these changes

2023-05-28 19:13 UTC, annonymousauthority approved these changes
LG

2023-05-28 19:13 UTC, merged