Taylor- adding password toggle
annonymousauthority/P2PCoder pull request #99
Opened 2023-05-25 17:57 UTC by TaylorDJones11

## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Refactor
- [ ] Bug Fix
- [ ] Optimization
- [ ] Documentation Update
- [ ] Other
  
  
## Description of what this Pull Request does
- Allows users to toggle between password visibility
- When the input value is erased, the icon is set back to default

## Related Tickets & Documents
-Closes: #98 

  
## QA Instructions, Screenshots, Recordings
![Password Toggle](https://github.com/annonymousauthority/P2PCoder/assets/72883059/64f9fcd0-8abc-4412-bfb3-c24e793ac549)

- I'm having issues with setting the input/svg back to the default if the user erases the input while the password is visible

2023-05-25 21:05 UTC, annonymousauthority requested changes
Please take the passWordToggleFunction to the component folder

2023-05-25 21:05 UTC, annonymousauthority commented on src/composables/passwordToggleFunction.js
> +  const eyeIcon = isPasswordVisible ? (
Put this in a useEffect hook

And it should watch fo change in `isPassword` `[isPasswordVisible]`

2023-05-25 21:05 UTC, annonymousauthority commented on src/composables/passwordToggleFunction.js
> +    setIsDefaultPassword(value === "" || !isPasswordVisible);
Do a check also here `setIsPasswordVisible(false)` if value === ""

2023-05-27 12:20 UTC, TaylorDJones11 commented
> Please take the passWordToggleFunction to the component folder

Everything has been resolved, but the dark/light mode is a mess 🥲

2023-05-28 11:09 UTC, annonymousauthority approved these changes
Referral to colors

2023-05-28 11:10 UTC, merged